In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from datetime import datetime, timedelta

# Assuming your dataset is in a CSV file named "weather_data.csv"
data = pd.read_csv("weather.csv")

# Extract relevant columns
data['date'] = pd.to_datetime(data['date'])
data = data[['date', 'temperaturemin', 'temperaturemax', 'precipitation']]

# Assuming 'date' is sorted, find the last date in the dataset
last_date = data['date'].max()

# Create a dataframe with future dates for prediction (next 7 days)
future_dates = pd.date_range(start=last_date + timedelta(days=1), periods=7, freq='D')
future_data = pd.DataFrame({'date': future_dates})

# Convert the 'date' column to the number of days since the reference date
reference_date = data['date'].min()
data['days_since_reference'] = (data['date'] - reference_date).dt.days
future_data['days_since_reference'] = (future_data['date'] - reference_date).dt.days

# Linear regression model for temperature min
model_temp_min = LinearRegression()
model_temp_min.fit(data[['days_since_reference']], data['temperaturemin'])

# Linear regression model for temperature max
model_temp_max = LinearRegression()
model_temp_max.fit(data[['days_since_reference']], data['temperaturemax'])

# Linear regression model for precipitation
model_precipitation = LinearRegression()
model_precipitation.fit(data[['days_since_reference']], data['precipitation'])

# Predict for the next 7 days
future_data['temperaturemin_pred'] = model_temp_min.predict(future_data[['days_since_reference']])
future_data['temperaturemax_pred'] = model_temp_max.predict(future_data[['days_since_reference']])
future_data['precipitation_pred'] = model_precipitation.predict(future_data[['days_since_reference']])

# Display the forecast
print("\n7-Day Weather Forecast:")
print(future_data[['date', 'temperaturemin_pred', 'temperaturemax_pred', 'precipitation_pred']])

7-Day Weather Forecast:
        date  temperaturemin_pred  temperaturemax_pred  precipitation_pred
0 2019-04-25            50.692944            70.897500            0.157011
1 2019-04-26            50.692953            70.897009            0.157023
2 2019-04-27            50.692963            70.896519            0.157035
3 2019-04-28            50.692973            70.896028            0.157047
4 2019-04-29            50.692983            70.895537            0.157059
5 2019-04-30            50.692993            70.895046            0.157071
6 2019-05-01            50.693003            70.894555            0.157083

In [2]:
data

,date,temperaturemin,temperaturemax,precipitation,days_since_reference
0,2011-02-13,25.0,61.0,0.00,1504
1,2011-02-16,34.0,63.0,0.00,1507
2,2011-02-18,52.0,78.1,0.00,1509
3,2011-03-03,35.1,53.1,0.00,1522
4,2011-03-16,46.9,64.0,0.05,1535
...,...,...,...,...,...
4492,2019-03-15,57.9,73.9,0.31,4456
4493,2019-03-17,35.1,57.0,0.00,4458
4494,2019-03-26,39.0,55.9,0.06,4467
4495,2019-04-09,61.0,73.9,0.04,4481
4496,2019-04-23,46.0,81.0,0.00,4495